### ISSUE TITLE
 How to shorten the Training Time

### ISSUE THREAD

**Issue by jiajiajiajiajiajiajiajiajia** [meyerscetbon/Deep-K-SVD#2]
Hello, dear author, I am a student majoring in Statistics and also a new coder. After reading your article, I have a strong interest in turning the classical algorithm K-SVD into a differentiable and learnable end-to-end depth architecture. And your research inspired my work, so I want to cite your article in my work and compare it with my results in the experiment comparison part. However, I encountered the problem of too long training time when reproducing your experimental results. I hope you can give me some guidance on how to shorten the training time. You mentioned in the article that it takes two days to train a model with Titan xp GPU. But after data processing, I have obtained a total of 29668032 pictures. Even though there are only three epochs, it will take me more than two months to train a model with 2080Ti GPU. At present, I only want to increase the print "every" in the experiment. I don't know if I made any mistakes in the operation? I hope you can reply my question as soon as possible.

**Comment by meyerscetbon** [comment]
Thank you for your interest in our work. During the training procedure you may have many sub images, but you should simply stop the learning stage after some times: 2 days is largely enough.

**Comment by jiajiajiajiajiajiajiajiajia** [comment]
Dear professor&nbsp;Scetbon
Thank you for your reply. According to your suggestion, i have retrained the model. As you have compared the parameters in the article, the selection of parameters plays a crucial role in the experimental results. So I'm worried that my parameter selection is different from your training model. When I use the default parameter in the source code: patch_size = 8, M = 16, T = 5, but the test result does not match the results in table1 and table3 in the article. But according to the parameters you mentioned in the article, if i choose to set the patch size to 64, M = 256, T = 7, K = 3, it prompts me that I need the display memory to be 256.Is there any problem? Or it really need so much GPU memory? Thank you again for your reply.&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;


&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Best regards,
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Ze'jia Wen&nbsp; &nbsp;&nbsp;a student from Southwest University in Chongqing, China
------------------&nbsp;原始邮件&nbsp;------------------

发件人:&nbsp;"meyerscetbon"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月23日(星期四) 凌晨4:19
收件人:&nbsp;"meyerscetbon/Deep-K-SVD"<Deep-K-SVD@noreply.github.com&gt;;
抄送:&nbsp;"文泽珈"<719732154@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [meyerscetbon/Deep-K-SVD]  How to shorten the Training Time (#2)





 
Thank you for your interest in our work. During the training procedure you may have many sub images, but you should simply stop the learning stage after some times: 2 days is largely enough.

**Comment by jiajiajiajiajiajiajiajiajia** [comment]
Dear professor Scetbon
Thank you for your reply. According to your suggestion, i have retrained the model. As you have compared the parameters in the article, the selection of parameters plays a crucial role in the experimental results. So I'm worried that my parameter selection is different from your training model. When I use the default parameter in the source code: patch_size = 8, M = 16, T = 5, but the test result does not match the results in table1 and table3 in the article. But according to the parameters you mentioned in the article, if i choose to set the patch size to 64, M = 256, T = 7, K = 3, it prompts me that I need the display memory to be 256.Is there any problem? Or it really need so much GPU memory? Thank you again for your reply.&nbsp;&nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Best regards,
Ze'jia Wen&nbsp; &nbsp;&nbsp;A student from Southwest University in Chongqing, China
------------------ 原始邮件 ------------------

发件人:&nbsp;"meyerscetbon"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月23日(星期四) 凌晨4:19
收件人:&nbsp;"meyerscetbon/Deep-K-SVD"<Deep-K-SVD@noreply.github.com&gt;;
抄送:&nbsp;"文泽珈"<719732154@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [meyerscetbon/Deep-K-SVD]  How to shorten the Training Time (#2)





 
Thank you for your interest in our work. During the training procedure you may have many sub images, but you should simply stop the learning stage after some times: 2 days is largely enough.

**Comment by meyerscetbon** [comment]
Please read carefully the paper as all the information you asked are explained there. You may select the following setting: patch_size = 8, M = 16, T = 7 and K = 3.

**Comment by jiajiajiajiajiajiajiajiajia** [comment]
Dear professor&nbsp;Scetbon
Thank you for your patience. The problem has been solved.&nbsp;I know my problem is that I didn't find out the relationship between the parameters in the code and the parameters in the article. I'm sorry for the trouble caused by my carelessness. Wish you have a nice day.




------------------ 原始邮件 ------------------
发件人:&nbsp;"meyerscetbon"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月25日(星期六) 凌晨2:01
收件人:&nbsp;"meyerscetbon/Deep-K-SVD"<Deep-K-SVD@noreply.github.com&gt;;
抄送:&nbsp;"文泽珈"<719732154@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [meyerscetbon/Deep-K-SVD]  How to shorten the Training Time (#2)





 
Please read carefully the paper as all the information you asked are explained there. Select  patch_size = 8, M = 16, T = 7 and K = 3.
